export enum ViewType {
  BROWSE = 'BROWSE',
  BROWSE_GENRES = 'BROWSE_GENRES',
  BROWSE_NEW_RELEASES = 'BROWSE_NEW_RELEASES',
  BROWSE_FEATURED = 'BROWSE_FEATURED',
  MY_PLAYLISTS = 'MY_PLAYLISTS',
  MY_ALBUMS = 'MY_ALBUMS',
  ALBUM = 'ALBUM',
  ALBUMS = 'ALBUMS',
  ARTIST = 'ARTIST',
  ARTISTS = 'ARTISTS',
  TRACKS = 'TRACKS',
  RECENTLY_PLAYED = 'RECENTLY_PLAYED',
  BROWSE_GENRES_PLAYLISTS = 'BROWSE_GENRES_PLAYLISTS',
  PLAYLIST = 'PLAYLIST',
}

export type ViewTypes =
  | 'BROWSE'
  | 'BROWSE_GENRES'
  | 'BROWSE_NEW_RELEASES'
  | 'BROWSE_FEATURED'
  | 'MY_PLAYLISTS'
  | 'MY_ALBUMS'
  | 'ALBUM'
  | 'ALBUMS'
  | 'ARTIST'
  | 'ARTISTS'
  | 'TRACKS'
  | 'RECENTLY_PLAYED'
  | 'BROWSE_GENRES_PLAYLISTS'
  | 'PLAYLIST';
